maintenancedapp:
  useDotenv: true
  component: '@sls-next/serverless-component@3.6.0'
  inputs:
    minifyHandlers: true
    removeOldLambdaVersions: true
    publicDirectoryCache:
      value: public, max-age=604800
      test: /\.(gif|jpe?g|png|txt|xml)$/i
    bucketName: ""
    cloudfront:
      distributionId: ""