import { Theme } from '@mui/material/styles';
import { makeStyles } from '@mui/styles';

const footerStyles = makeStyles((theme: Theme) => ({
  footerMainContainer: {
    maxWidth: '100%',
    paddingTop: 49,
    background: `${theme.palette.background.purple}`,
  },
  footerWrapper: {
    width: 1160,
    padding: 0,
    margin: '0 auto',
    '@media(max-width: 1280px)': { width: '100%' },
  },
  primaryFooter: {
    display: 'flex',
    '@media(max-width: 1200px)': { flexDirection: 'column' },
  },
  logoSection: {
    boxSizing: 'content-box',
    width: '44%',
    paddingRight: 73,
    '@media(max-width: 1200px)': {
      boxSizing: 'border-box',
      width: '100%',
      padding: 0,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    '@media(max-width: 640px)': {
      flexDirection: 'column',
      alignItems: 'flex-start',
    },
  },
  logo: {
    '& img': { width: 232 },
    '& > span': {
      margin: '12px 0 24px',
      display: 'block',
      color: '#EFE3F1',
      fontFamily: 'MuliLight',
      fontSize: 16,
      fontStyle: 'italic',
      fontWeight: 200,
      letterSpacing: -0.08,
      lineHeight: '14px',
    },
  },
  socialIconsNewsletterContainer: {
    '& ul': {
      padding: 0,
      margin: 0,
      display: 'flex',
      '& li': {
        marginRight: 14,
        listStyle: 'none',
        '& svg': {
          boxSizing: 'content-box',
          padding: 7,
          borderRadius: '50%',
          backgroundColor: `${theme.palette.alertMsg.pendingBorder}`,
          color: `${theme.palette.common.white}`,
          fontSize: 19,
          '&:hover': { backgroundColor: '#7F1BA4' },
        },
        '& img': {
          boxSizing: 'content-box',
          padding: 7,
          borderRadius: '50%',
          backgroundColor: `${theme.palette.alertMsg.pendingBorder}`,
          color: `${theme.palette.common.white}`,
          fontSize: 19,
          '&:hover': { backgroundColor: '#7F1BA4' },
        },
        '&:last-of-type': { marginRitgh: 0 },
      },
    },
    '@media(max-width: 640px)': { marginTop: 10 },
  },
  newsLetterContainer: {
    marginTop: 56,
    '& span': {
      marginBottom: 9,
      display: 'block',
      color: '#B3B0B0',
      fontFamily: 'MuliSemiBold',
      fontSize: 14,
      lineHeight: '18px',
    },
    '& .MuiTextField-root': {
      width: 228,
      '& input': {
        boxSizing: 'border-box',
        width: 228,
        height: 48,
        border: '2px solid #D9D9D9',
        borderRadius: 3,
        backgroundColor: `${theme.palette.common.white}`,
        color: `${theme.palette.textAdvanced.dark}`,
        fontFamily: 'MuliSemiBold',
        fontSize: 14,
        lineHeight: '24px',
      },
      '& fieldset': { top: '-15px' },
    },
    '& button': {
      padding: '16px 26px',
      borderRadius: 3,
      marginLeft: 16,
      backgroundColor: `${theme.palette.alertMsg.pendingBorder}`,
      boxShadow: '0 1px 1px 0 rgba(0,0,0,0.14), 0 2px 1px -1px rgba(0,0,0,0.12), 0 1px 3px 0 rgba(0,0,0,0.2)',
      color: `${theme.palette.common.white}`,
      fontFamily: 'MuliBold',
      fontSize: 14,
      lineHeight: '16px',
      '&:hover': { backgroundColor: '#7F1BA4' },
    },
    '@media(max-width: 1200px)': { marginTop: 0 },
  },
  footerRightSideLinks: {
    width: '100%',
    display: 'flex',
    '@media(max-width: 1200px)': {
      borderTop: '1px solid #8860D0',
      paddingTop: 25,
      marginTop: 25,
    },
    '@media(max-width: 640px)': { flexDirection: 'column' },
  },
  footerLinksContainer: {
    width: '25%',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    '& > span': {
      marginBottom: 24,
      display: 'block',
      color: `${theme.palette.textAdvanced.grey2}`,
      fontFamily: 'MuliBold',
      fontSize: 18,
      lineHeight: '24px',
    },
    '@media(max-width: 640px)': {
      width: '100%',
      marginBottom: 40,
    },
  },
  footerLinks: {
    padding: 0,
    display: 'flex',
    '& a': {
      padding: 0,
      marginBottom: 14,
      display: 'block',
      color: '#EFE3F1',
      fontFamily: 'MuliRegular',
      fontSize: 14,
      letterSpacing: -0.07,
      lineHeight: '14px',
      '&:last-of-type span': { marginBottom: 0 },
    },
  },
  secondaryFooter: {
    borderTop: '1px solid #8860D0',
    marginTop: 34,
    '& > div': {
      padding: '24px 0',
      display: 'flex',
      justifyContent: 'space-between',
      '@media(max-width: 640px)': {
        width: '100%',
        flexDirection: 'column',
        alignItems: 'center',
      },
    },
    '& span': {
      color: `${theme.palette.text.secondary}`,
      fontFamily: 'MuliSemiBold',
      fontSize: 16,
      lineHeight: '32px',
      opacity: '50%',
    },
    '& p': {
      margin: 0,
      color: `${theme.palette.text.secondary}`,
      fontFamily: 'MuliSemiBold',
      fontSize: 16,
      lineHeight: '32px',
      opacity: '50%',
    },
    '& a': { textDecoration: 'underline' },
  },
}));

export default footerStyles;
